### ISSUE TITLE
Mapping tiles

### ISSUE THREAD

**Issue by eltonteb** [recogito/geotagger#3]
Facility to choose mapping tiles to match the gazetteer look up and/or mapview

**Comment by rsimon** [comment]
For this round, the limitation will remain that the UI will only offer a single base map. (I.e. no layer switcher in the gazetteer search.) However, the base map is now configurable in the plugin admin interface. 

<img width="705" alt="Bildschirmfoto 2024-04-02 um 11 14 01" src="https://github.com/recogito/geotagger/assets/470971/11c183cf-ef98-4308-a453-0c525c9fd0aa">

The user can set any GoogleMaps-compatible X/Y/Z tileset, if they know the tileset URL. The plugin also comes with a set of presets to choose from, currently OpenStreetMap, Consortium of Ancient World Mappers (formerly AWMC map tiles), Digital Atlas of the Roman Empire.
